
package proyecto_final_progra;

import javax.swing.JOptionPane;
import static proyecto_final_progra.BuscarCliente.confirmacion;

/**
 *
 * @author danovargas
 */
public class BuscarLibro extends javax.swing.JFrame {

    /**
     * Creates new form BuscarLibro
     */
    public BuscarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BusquedaIDBtn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InventarioDisplayField = new javax.swing.JTextArea();
        BusquedaPublicacionBtn = new javax.swing.JToggleButton();
        Cerrar = new javax.swing.JToggleButton();
        BusquedaLibroBtn1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Silom", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar libro");

        BusquedaIDBtn.setText("Numero de Id");
        BusquedaIDBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaIDBtnMouseClicked(evt);
            }
        });

        InventarioDisplayField.setColumns(20);
        InventarioDisplayField.setRows(5);
        jScrollPane1.setViewportView(InventarioDisplayField);

        BusquedaPublicacionBtn.setText("Año de publicacion");
        BusquedaPublicacionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaPublicacionBtnMouseClicked(evt);
            }
        });
        BusquedaPublicacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaPublicacionBtnActionPerformed(evt);
            }
        });

        Cerrar.setText("Cerrar");
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });

        BusquedaLibroBtn1.setText("Nombre de Libro");
        BusquedaLibroBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaLibroBtn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BusquedaPublicacionBtn)
                        .addGap(89, 89, 89)
                        .addComponent(BusquedaLibroBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BusquedaIDBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BusquedaPublicacionBtn)
                            .addComponent(BusquedaLibroBtn1))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BusquedaIDBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(192, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int alquiler, costoDiario, costoFinal;
    static Inventario biblioteca = new Inventario();
    Clientes baseClientes = new Clientes();
    int i, e, cont;
    static IngresoLibro bibliotecaRecientes = new IngresoLibro();
    boolean error, confirmacion;

    private void BusquedaIDBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaIDBtnMouseClicked
        // TODO add your handling code here:
        
        //este metodo se encarga de buscar dentro de las listas que estan creadas y las q han sido creadas,
        //y encontrar basado en los parametros que se definen en la interfaz grafica.
        
       try {
            biblioteca.llenarLibro();

            int busqueda = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del libro"));

            for (i = 0; i < biblioteca.libros.length; i++) {
                if (biblioteca.libros[i] != null) {
                    if (biblioteca.libros[i].id == (busqueda)) {
                        InventarioDisplayField.setText("" + biblioteca.libros[i]);
                        confirmacion = true;
                        break;
                    } else {
                    }
                } else {
                }
            }
        } catch (NullPointerException e) {
        } catch (java.lang.NumberFormatException e) {

        }
        if (i == 15) {
            confirmacion = false;
            JOptionPane.showMessageDialog(null, "No se encontro el libro");
        }

    }//GEN-LAST:event_BusquedaIDBtnMouseClicked

    private void BusquedaPublicacionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaPublicacionBtnMouseClicked
        // TODO add your handling code here:
        try {
            biblioteca.llenarLibro();

            int busqueda = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el año de publicacion del libro"));

            for (i = 0; i < biblioteca.libros.length; i++) {
                if (biblioteca.libros[i] != null) {
                    if (biblioteca.libros[i].publicacion == (busqueda)) {
                        InventarioDisplayField.setText("" + biblioteca.libros[i]);
                        confirmacion = true;
                        break;
                    } else {
                    }
                } else {
                }
            }
        } catch (NullPointerException e) {
        } catch (java.lang.NumberFormatException e) {

        }
        if (i == 15) {
            confirmacion = false;
            JOptionPane.showMessageDialog(null, "No se encontro el libro");
        }


    }//GEN-LAST:event_BusquedaPublicacionBtnMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        // TODO add your handling code here:
        MainMenu ejecuta = new MainMenu();
        ejecuta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarMouseClicked

    private void BusquedaLibroBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaLibroBtn1MouseClicked

        try {
            biblioteca.llenarLibro();

            String busqueda = JOptionPane.showInputDialog("Ingrese el nombre del libro");

            for (i = 0; i < biblioteca.libros.length; i++) {
                if (biblioteca.libros[i] != null) {
                    if (biblioteca.libros[i].nombre.equals(busqueda)) {
                        InventarioDisplayField.setText("" + biblioteca.libros[i]);
                        confirmacion = true;
                        break;
                    } else {
                    }
                } else {
                }
            }
        } catch (NullPointerException e) {
        } catch (java.lang.NumberFormatException e) {

        }
        if (i == 15) {
            confirmacion = false;
            JOptionPane.showMessageDialog(null, "No se encontro el libro");
        }

    }//GEN-LAST:event_BusquedaLibroBtn1MouseClicked

    private void BusquedaPublicacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaPublicacionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaPublicacionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BusquedaIDBtn;
    private javax.swing.JToggleButton BusquedaLibroBtn1;
    private javax.swing.JToggleButton BusquedaPublicacionBtn;
    private javax.swing.JToggleButton Cerrar;
    private javax.swing.JTextArea InventarioDisplayField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
