
package proyecto_final_progra;

import javax.swing.JOptionPane;
import static proyecto_final_progra.BuscarLibro.bibliotecaRecientes;

/**
 *
 * @author danovargas
 */
public class IngresoLibro extends javax.swing.JFrame {

    /**
     * Creates new form IngresoLibro
     */
    public IngresoLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LibroTxt = new javax.swing.JTextField();
        AutorTxt = new javax.swing.JTextField();
        AnnoTxt = new javax.swing.JTextField();
        EditorialTxt = new javax.swing.JTextField();
        PrecioTxt = new javax.swing.JTextField();
        IdTxt = new javax.swing.JTextField();
        AgregarBtn = new javax.swing.JToggleButton();
        CerrarBtn = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Silom", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso Libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 530, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Libro");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 155, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Autor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 201, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Editorial");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 287, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año de publicacion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 333, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 245, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 113, -1, -1));
        jPanel1.add(LibroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 109, 272, -1));
        jPanel1.add(AutorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 151, 272, -1));
        jPanel1.add(AnnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 241, 272, -1));
        jPanel1.add(EditorialTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 197, 272, -1));
        jPanel1.add(PrecioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 283, 272, -1));
        jPanel1.add(IdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 325, 272, -1));

        AgregarBtn.setText("Agregar");
        AgregarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarBtnMouseClicked(evt);
            }
        });
        jPanel1.add(AgregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 396, -1, -1));

        CerrarBtn.setText("Cerrar");
        CerrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarBtnMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 396, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bla4.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void AgregarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarBtnMouseClicked
        // TODO add your handling code here:
        
        //este metodo se encarga de adjuntar nuevos objetos tipo libro a la lista que ya 
        //se habia creado con datos fijos.
        
        try {
            String libroName = LibroTxt.getText();
            String autorName = AutorTxt.getText();
            String editorialName = EditorialTxt.getText();
            int idName = Integer.parseInt(IdTxt.getText());
            int precioName = Integer.parseInt(PrecioTxt.getText());
            int annoName = Integer.parseInt(AnnoTxt.getText());

            Inventario.libros[Inventario.cont] = new Libro(idName, annoName, precioName, libroName, autorName, editorialName);
            Inventario.cont++;

            JOptionPane.showMessageDialog(null, "Informacion se guardo");
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Out of bounds");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "no se pueden ingresar numeros en el año");
        }

    }//GEN-LAST:event_AgregarBtnMouseClicked

    private void CerrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarBtnMouseClicked
        // TODO add your handling code here:

        MainMenu ejecuta = new MainMenu();
        ejecuta.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_CerrarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AgregarBtn;
    private javax.swing.JTextField AnnoTxt;
    private javax.swing.JTextField AutorTxt;
    private javax.swing.JToggleButton CerrarBtn;
    private javax.swing.JTextField EditorialTxt;
    private javax.swing.JTextField IdTxt;
    private javax.swing.JTextField LibroTxt;
    private javax.swing.JTextField PrecioTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
