
package proyecto_final_progra;

import javax.swing.JOptionPane;

/**
 *
 * @author danovargas
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        HeaderLoginPage = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JLabel();
        NombreTxtField = new javax.swing.JTextField();
        IDtxt = new javax.swing.JLabel();
        PasswordTxtField = new javax.swing.JPasswordField();
        VerificarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        HeaderLoginPage.setFont(new java.awt.Font("Silom", 2, 18)); // NOI18N
        HeaderLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        HeaderLoginPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLoginPage.setText("Ingrese sus datos");
        jPanel1.add(HeaderLoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 488, -1));

        NombreTxt.setBackground(new java.awt.Color(255, 255, 255));
        NombreTxt.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        NombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        NombreTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NombreTxt.setText("Nombre:");
        jPanel1.add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 140, -1));
        jPanel1.add(NombreTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, -1));

        IDtxt.setBackground(new java.awt.Color(255, 255, 255));
        IDtxt.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        IDtxt.setForeground(new java.awt.Color(255, 255, 255));
        IDtxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDtxt.setText("ID:");
        jPanel1.add(IDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 140, -1));
        jPanel1.add(PasswordTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 200, -1));

        VerificarBtn.setText("Verificar");
        VerificarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerificarBtnMouseClicked(evt);
            }
        });
        jPanel1.add(VerificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 301));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerificarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerificarBtnMouseClicked
        //Esta ventana se creo para intentar hacer el UI/UX mas amigable para el usuario.
        //su principal tarea es crear una interfaz grafica que permita al usuario entrar de forma segura al programa
        try {
            for (int i = 0; i == 0; i++) {
                String nombre = NombreTxtField.getText();
                int id = Integer.parseInt(PasswordTxtField.getText());

                if (id == 1155 && nombre.contains("Juan")) {
                    JOptionPane.showMessageDialog(null, "Su ingreso ha sido correcto.");
                    MainMenu ejecuta = new MainMenu();
                    ejecuta.setVisible(true);
                    this.dispose();

                }else{
                    JOptionPane.showMessageDialog(null, "Ingreso erroneo, intente de nuevo.");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor no utilice simbolos ni letras en la contraseña");
        }


    }//GEN-LAST:event_VerificarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderLoginPage;
    private javax.swing.JLabel IDtxt;
    private javax.swing.JLabel NombreTxt;
    private javax.swing.JTextField NombreTxtField;
    private javax.swing.JPasswordField PasswordTxtField;
    private javax.swing.JButton VerificarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
